language: ruby

rvm:
  - 2.2

install:
  - gem install awesome_bot

script:
  - awesome_bot readme.md --allow-dupe --white-list irc.lc,img.shields.io,demo.thelounge.chat,awesome.re,quassel-irc.org,demo.convos.by

notifications:
  email: false
